[project]
name = "unity-robot-ml-agent"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "gentrix", email = "t01020277877@gmail.com" }
]
requires-python = ">=3.14"
dependencies = []

[project.scripts]
unity-robot-ml-agent = "unity_robot_ml_agent:main"

[build-system]
requires = ["uv_build>=0.12.10,<0.13.0"]
build-backend = "uv_build"
